### ISSUE TITLE
大佬，能否把这个项目里的上拉刷新，下拉加载提出来做成一个模块用呢？

### ISSUE THREAD

**Issue by atjiu** [liuguanhua/react-cnode-project#1]
这个项目里的上拉加载下拉刷新效果很赞，而且从列表跳转出去了，回来还能记住之前的位置，希望能把这个功能提出来，相信很多人用react都有这个需求

**Comment by liuguanhua** [comment]
想法的确不错😄，其实上拉刷新，下拉加载这个功能是一个模块，具体可以参考这个npm包[react-touch-loader](https://github.com/Broltes/react-touch-loader)。
   从列表进入详情页，回退记住之前的位置具体实现思路是将加载过的数据和滚动条的位置保存在redux中，然后回退进入列表时取redux的数据[详见](https://github.com/liuguanhua/react-cnode-project/blob/f5df172a0e7dd34e5ef5101df9af7fd2b0bfe512/src/component/plugin/touch-loadmore/LoadMore.jsx#L13)！

**Comment by atjiu** [comment]
好的，谢谢
